baseurl = "https://blist.vercel.app"
metaDataFormat = "yaml"
title = "Blist Multilingual Theme"
theme = "blist"

DefaultContentLanguage = "zh"
DefaultContentLanguageInSubdir = true
# disableLanguages = ['de', 'en']
[languages]
  [languages.zh]
    contentDir = "content/zh" #English
    weight = 1
    languageName = "ä¸­æ–‡"
    [languages.zh.params]
      introTitle = "My name is Francis, I'm a sinner ðŸ’”ðŸ’”ðŸ’”"
      introSubtitle = "Sister Theresa advises me to write a diary about my life. I'm a catholic and currently under demon possessed. I'm in the process of drug recovery, I have many dark pasts and broken memories, but that all doesn't matter now cos I know I'll be healed. I want to discover Jesus through my suffering time."
      introPhoto = "/mypicture.jpeg"
      logo = "/logo.png"
    [[languages.zh.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.zh.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.zh.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.zh.menu.main]]
        name = "Top Post"
        url = "/zh/blog/emoji-support/"
        weight = 4

#  [languages.de]
#    contentDir = "content/de" # Deutsch
#    weight = 2
#    languageName = "Deutsch"
#    title = "Blist (mehrsprachig)"
#    description = "Modernes Blog-Theme fÃ¼r Ihre Hugo-Site."
#    [languages.de.params]
#      introTitle = "Hallo, ich bin Katheryn Fox"
#      introSubtitle = "26-jÃ¤hrige Junior-Entwicklerin, die SpaÃŸ an sozialen Kartenspielen, Bloggen und Malen hat"
#      introPhoto = "/picture.jpg"
#      logo = "/blist-logo-de.png"
#    [[languages.de.menu.main]]
#        name = "Blog"
#        url = "blog"
#        weight = 1

#    [[languages.de.menu.main]]
#        name = "Ãœber mich"
#        url = "page/about/"
#        weight = 2

#    [[languages.de.menu.main]]
#        name = "Tags"
#        url = "tags"
#        weight = 3

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright Â© 2021 - Katheryn Fox Â· All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow me"
  description = "I work on everything coding and tweet developer memes"
  twitter = "https://twitter.com/"
  linkedin = "https://linkedin.com/in/"
  xing = "https://www.xing.com/profile/"
  github = "https://github.com/"
  medium = "https://medium.com/"
  reddit = "https://reddit.com/"
  dribbble = "https://dribbble.com/"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
